### ISSUE TITLE
Review 1: Error Syntax

### ISSUE THREAD

**Issue by priyandari** [adnan-akbr/Tubes_Progkom_5A#2]
F:\Dropbox\01 PERKULIAHAN\Program Komputer\Modul_Kuliah>C:/ProgramData/Anaconda3/Scripts/activate

(base) F:\Dropbox\01 PERKULIAHAN\Program Komputer\Modul_Kuliah> cmd /C "C:\ProgramData\Anaconda3\python.exe c:\Users\Yusuf\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\no_wheels\debugpy\launcher 49766 -- "f:\Dropbox\01 PERKULIAHAN\Program Komputer\UAS Prokom 2020\Review 1\Tubes_Progkom_1A-master\Program_Olshop_Happy_Fresh.py" "
  File "f:\Dropbox\01 PERKULIAHAN\Program Komputer\UAS Prokom 2020\Review 1\Tubes_Progkom_1A-master\Program_Olshop_Happy_Fresh.py", line 239
    elif MP == "COD"
                   ^
SyntaxError: invalid syntax

**Comment by priyandari** [comment]
Jenis buah apa yang ingin Anda beli?: 4
Masukkan jumlah buah (per kg): 2.5
Traceback (most recent call last):
  File "a1_olshop.py", line 89, in <module>
    qnty = int(input("Masukkan jumlah buah (per kg): "))
ValueError: invalid literal for int() with base 10: '2.5'

**Comment by priyandari** [comment]
Produk-produk yang kami tawarkan :
1.Daging Sapi
2.Buah
3.Sayur
Input nomer jenis belanjaan Anda(dalam angka) : 3
1. Brokoli (1kg)                 = 40000
Jenis sayur apa yang ingin Anda beli?: 1
2. Wortel (1kg)                  = 20000
Jenis sayur apa yang ingin Anda beli?:
Traceback (most recent call last):
  File "a1_olshop.py", line 109, in <module>
    option = int(input("Jenis sayur apa yang ingin Anda beli?: "))
ValueError: invalid literal for int() with base 10: ''

**Tidak ingin membeli wortel** caranya bagaimana

**Comment by AhnafRafif** [comment]
Untuk SyntaxEror sudah kami perbaiki, untuk pembelian jumlah buah sudah kami ganti dengan float sehingga pembelian tidak bulat per kg nya

**Comment by priyandari** [comment]
Pembelian float belum selesai

**Comment by adnan-akbr** [comment]
for isi in listDaging:
                    print(isi)
                option = int(input("Jenis daging apa yang ingin Anda beli?: "))
                if option == 1:
                    qnty = float(input("Masukkan jumlah daging (per kg): "))
                    total = qnty * 170000
                    listnamabelanjaan.append("Tenderloin")
                    listhargabelanjaan.append(qnty)
                elif option == 2:
                    qnty = float(input("Masukkan jumlah daging (per kg): "))
                    total = qnty * 150000
                    listnamabelanjaan.append("Sirloin")
                    listhargabelanjaan.append(qnty)
             **elif option == 3:
                    qnty = int(input("Masukkan jumlah daging (per kg): "))
                    total = qnty * 140000
                    listnamabelanjaan.append("Rib eye")
                    listhargabelanjaan.append(qnty)**
                elif option == 4:
                    qnty = float(input("Masukkan jumlah daging (per kg): "))
                    total = qnty * 120000
                    listnamabelanjaan.append("Brisket")
                    listhargabelanjaan.append(qnty)
                elif option == 5:
                    qnty = float(input("Masukkan jumlah daging (per kg): "))
                    total = qnty * 130000
                    listnamabelanjaan.append("Oxtail")
                    listhargabelanjaan.append(qnty)




maaf pak yusuf karena kurang ketelitian kami. Hanya dibagian daging Rib eye masih menggunakan int. sudah kami perbaiki, terima kasih pak
