### ISSUE TITLE
Logic program disesuaikan dengan online shop

### ISSUE THREAD

**Issue by priyandari** [adnan-akbr/Tubes_Progkom_5A#3]
kalau di online shop, pilih dahulu barang2 baru chekout dan nanti di total.
bukan 1 ditotal, 1 pilih ditotal..

Sekalian tambahkan tampilan NOTA pembelian jika beli beberapa jenis barang

**Comment by AhnafRafif** [comment]
Untuk nota sudah kami tambahkan dan logic program sudah kami sesuaikan pak
